version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    container_name: 
      prisma
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: 90bSYQAYEvcFBWGh118tL28fIGPXvotMRZxDvrbOc9fKAHlTVPymPraBYMMilmF7ADMpVRwY4mh14rcGpwx8p3xjXAbzGn1G
        databases:
          default:
            connector: postgres
            host: postgres-db
            database: forum
            user: forum
            password: password
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true

networks: 
  default:
    external:
      name: forumapp_forum-graphql
